name: "LibreLink Up to Nightscout Sync"
version: "1.1.0"
slug: "libre_nightscout_sync"
description: "Synchronize LibreLink Up glucose data with Nightscout"
url: "https://github.com/bfreire/libre-nightscout-sync"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
map:
  - addon_config:rw
options:
  librelink_username: ""
  librelink_password: ""
  librelink_region: "EU"
  nightscout_url: ""
  nightscout_api_token: ""
  sync_interval: 5
schema:
  librelink_username: str
  librelink_password: password
  librelink_region: list(EU|US)
  nightscout_url: str
  nightscout_api_token: password
  sync_interval: int(1,60)
advanced: true
build_from: "ghcr.io/home-assistant/{arch}-base:3.16" 